// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY UnitGenerator. DO NOT CHANGE IT.
// </auto-generated>
#pragma warning disable CS8669
using System;
 
using MessagePack;
using MessagePack.Formatters;

namespace Sample
{
 
    [MessagePackFormatter(typeof(PlayerIdMessagePackFormatter))]
    [System.ComponentModel.TypeConverter(typeof(PlayerIdTypeConverter))]
    readonly partial struct PlayerId : IEquatable<PlayerId> 
    {
        readonly System.Ulid value;

        public System.Ulid AsPrimitive() => value;

        public PlayerId(System.Ulid value)
        {
            this.value = value;
        }


        public static explicit operator System.Ulid(PlayerId value)
        {
            return value.value;
        }

        public static explicit operator PlayerId(System.Ulid value)
        {
            return new PlayerId(value);
        }

        public bool Equals(PlayerId other)
        {
            return value.Equals(other.value);
        }

        public override bool Equals(object obj)
        {
            if (obj == null) return false;
            var t = obj.GetType();
            if (t == typeof(PlayerId))
            {
                return Equals((PlayerId)obj);
            }
            if (t == typeof(System.Ulid))
            {
                return value.Equals((System.Ulid)obj);
            }

            return value.Equals(obj);
        }

        public override int GetHashCode()
        {
            return value.GetHashCode();
        }

        public override string ToString()
        {
            return value.ToString();
        }

        public static bool operator ==(in PlayerId x, in PlayerId y)
        {
            return x.value.Equals(y.value);
        }

        public static bool operator !=(in PlayerId x, in PlayerId y)
        {
            return !x.value.Equals(y.value);
        }


        public static readonly PlayerId Empty = default(PlayerId);
        
        public static PlayerId New()
        {
            return new PlayerId(Ulid.NewUlid());
        }

        public static PlayerId NewPlayerId()
        {
            return new PlayerId(Ulid.NewUlid());
        }









 
        // UnitGenerateOptions.MessagePackFormatter
        private class PlayerIdMessagePackFormatter : IMessagePackFormatter<PlayerId>
        {
            public void Serialize(ref MessagePackWriter writer, PlayerId value, MessagePackSerializerOptions options)
            {
                options.Resolver.GetFormatterWithVerify<System.Ulid>().Serialize(ref writer, value.value, options);
            }

            public PlayerId Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
            {
                return new PlayerId(options.Resolver.GetFormatterWithVerify<System.Ulid>().Deserialize(ref reader, options));
            }
        }



        // Default
        private class PlayerIdTypeConverter : System.ComponentModel.TypeConverter
        {
            private static readonly Type WrapperType = typeof(PlayerId);
            private static readonly Type ValueType = typeof(System.Ulid);

            public override bool CanConvertFrom(System.ComponentModel.ITypeDescriptorContext context, Type sourceType)
            {
                if (sourceType == WrapperType || sourceType == ValueType)
                {
                    return true;
                }

                return base.CanConvertFrom(context, sourceType);
            }

            public override bool CanConvertTo(System.ComponentModel.ITypeDescriptorContext context, Type destinationType)
            {
                if (destinationType == WrapperType || destinationType == ValueType)
                {
                    return true;
                }

                return base.CanConvertTo(context, destinationType);
            }

            public override object ConvertFrom(System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value)
            {
                if (value != null)
                {
                    var t = value.GetType();
                    if (t == typeof(PlayerId))
                    {
                        return (PlayerId)value;
                    }
                    if (t == typeof(System.Ulid))
                    {
                        return new PlayerId((System.Ulid)value);
                    }
                }

                return base.ConvertFrom(context, culture, value);
            }

            public override object ConvertTo(System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value, Type destinationType)
            {
                if (value is PlayerId wrappedValue)
                {
                    if (destinationType == WrapperType)
                    {
                        return wrappedValue;
                    }

                    if (destinationType == ValueType)
                    {
                        return wrappedValue.AsPrimitive();
                    }
                }

                return base.ConvertTo(context, culture, value, destinationType);
            }
        }
    }
}
